### ISSUE TITLE
Generate subnet mask based on CIDR instead of providing in settings

### ISSUE THREAD

**Issue by belminf** [belminf/kaslan#32]
in kaslan.yaml, instead of:

```
172.20.37.0/24:
  gateway: 172.20.37.1
  subnet: 255.255.255.0
  dns: 172.20.1.10
  vlan: 1720
```

Should be:

```
172.20.37.0/24:
  gateway: 172.20.37.1
  dns: 172.20.1.10
  vlan: 1720
```
